# Generated by Django 6.0.1 on 2026-01-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_city_user_country_user_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='show_phone',
            field=models.BooleanField(default=False),
        ),
        # migrations.AlterField(
        #     model_name='user',
        #     name='country',
        #     field=models.CharField(blank=True, max_length=2),
        # ),
    ]
