# Generated by Django 6.0.1 on 2026-01-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_show_email_user_show_phone_alter_user_country'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='user',
        #     name='country',
        #     field=models.CharField(blank=True, max_length=100),
        # ),
    ]
