# Generated by Django 6.0.1 on 2026-01-24 10:22

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_country'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='user',
        #     name='country',
        #     field=django_countries.fields.CountryField(blank=True, max_length=2),
        # ),
    ]
