trigger:
  branches:
    include:
      - main

variables:
  dockerHubUser: aquils        # 👈 replace with your DockerHub username
  imageName: bitegenius

pool:
  vmImage: ubuntu-latest

stages:
- stage: BuildAndPush
  displayName: Build and Push Docker Image
  jobs:
  - job: DockerCI
    displayName: Docker Build and Push
    steps:
    - checkout: self

    - task: Docker@2
      displayName: Build and Push Image
      inputs:
        command: buildAndPush
        containerRegistry: dockerhub-connection
        repository: $(dockerHubUser)/$(imageName)
        dockerfile: Dockerfile
        tags: |
          latest
          $(Build.BuildId)
