apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bitegenius-ingress
  namespace: bitegenius
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - bitegenius.local
    secretName: bitegenius-tls
  rules:
  - host: bitegenius.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bitegenius-service
            port:
              number: 80
