# Generated by Django 6.0.1 on 2026-01-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_pantryitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_user_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(blank=True, default='Unnamed recipe', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='prep_time_minutes',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
