# Generated by Django 6.0.1 on 2026-01-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_recipe_is_user_submitted_alter_recipe_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='steps',
            field=models.TextField(blank=True, help_text='One step per line'),
        ),
    ]
