# Generated by Django 6.0.1 on 2026-01-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_pantryitem_user_alter_pantryitem_ingredient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyplan',
            name='session_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
