# Generated by Django 6.0.1 on 2026-01-21 19:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_alter_pantryitem_session_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weeklyplan',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='weeklyplan',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'week_start'), name='unique_weekly_plan_per_user'),
        ),
        migrations.AddConstraint(
            model_name='weeklyplan',
            constraint=models.UniqueConstraint(condition=models.Q(('session_id__isnull', False)), fields=('session_id', 'week_start'), name='unique_weekly_plan_per_session'),
        ),
    ]
