# Generated by Django 6.0.1 on 2026-01-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_alter_weeklyplan_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyplan',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
